import datetime
import subprocess
from pathlib import Path
from SCons.Script import DefaultEnvironment

env = DefaultEnvironment()


def _git_short_hash(cwd: Path) -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(cwd),
            stderr=subprocess.DEVNULL,
        )
        return out.decode("utf-8").strip()
    except Exception:
        return "unknown"


def generate_build_header(env_local):
    project_dir = Path(env_local["PROJECT_DIR"])
    header_path = project_dir / "src" / "build_info.h"
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    git_hash = _git_short_hash(project_dir)
    content = (
        "// Auto-generated by scripts/build_info.py\n"
        "#pragma once\n"
        f'#define BUILD_TIMESTAMP "{ts}"\n'
        f'#define BUILD_GIT_HASH "{git_hash}"\n'
    )
    header_path.write_text(content, encoding="utf-8")


def before_build(source, target, **kwargs):
    generate_build_header(env)


# Generate immediately (for clean runs) and attach pre-action to buildprog
generate_build_header(env)
env.AddPreAction("buildprog", before_build)
